---
pool: 
  vmImages: 'ubuntu-latest'

jobs: 
  - job: Buildspc
    displayName: Build Code
  - task: Maven@3
    inputs:
      mavenPOMFile: 'pom.xml'
      goals: 'package'
      publishJUnitResults: true 
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'path'
      jdkVersionOption: '1.17'
      jdkDirectory: 'usr/lib/jvm/java-17-openjdk-amd64'
      mavenVersionOption: Path
      mavenDirectory: '/usr/share/maven'